=== fabiogabriel5555/GAPE/target/browser-tomcat10/webapps/GAPE/WEB-INF/classes/config/xsd/transversal/multiYearCalendar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="calendar">
    <xs:annotation>
      <xs:documentation> Main container that allows multiple years. Example: &lt;calendar&gt;...&lt;/calendar&gt;</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ano" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation> Defines a specific year in the calendar. Unlimited years are allowed.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="month" maxOccurs="12">
                <xs:annotation>
                  <xs:documentation> Represents to month of the year. Maximum of 12 occurrences.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="day" maxOccurs="31">
                      <xs:annotation>
                        <xs:documentation> Represents an individual day. Maximum of 31 per month.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:choice>
                            <xs:annotation>
                              <xs:documentation> Rule: the day must be Workday, Weekend, or Holiday.</xs:documentation>
                            </xs:annotation>
                            <xs:element name="workday" type="xs:string" fixed="">
                              <xs:annotation>
                                <xs:documentation> Regular workday. Must be empty: &lt;workday/&gt;</xs:documentation>
                              </xs:annotation>
                            </xs:element>
                            <xs:element name="weekend" type="xs:string" fixed="">
                              <xs:annotation>
                                <xs:documentation> Saturday or Sunday. Must be empty: &lt;weekend/&gt;</xs:documentation>
                              </xs:annotation>
                            </xs:element>
                            <xs:element name="holiday">
                              <xs:annotation>
                                <xs:documentation> Official festive day or national holiday.</xs:documentation>
                              </xs:annotation>
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="New Year"/>
                                  <xs:enumeration value="Carnival Tuesday"/>
                                  <xs:enumeration value="Good Friday"/>
                                  <xs:enumeration value="Easter"/>
                                  <xs:enumeration value="Freedom Day"/>
                                  <xs:enumeration value="Labor Day"/>
                                  <xs:enumeration value="Corpus Christi"/>
                                  <xs:enumeration value="Portugal Day"/>
                                  <xs:enumeration value="Assumption of Mary"/>
                                  <xs:enumeration value="Republic Day"/>
                                  <xs:enumeration value="All Saints Day"/>
                                  <xs:enumeration value="Restoration of Independence"/>
                                  <xs:enumeration value="Immaculate Conception"/>
                                  <xs:enumeration value="Christmas"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:element>
                          </xs:choice>

                          <xs:element name="container" minOccurs="0">
                            <xs:annotation>
                              <xs:documentation> Optional block for additional day information.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:all>
                                <xs:element name="agenda" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation> Personal notes or general commitments.</xs:documentation>
                                  </xs:annotation>
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:any minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="academic" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation> School events, for example class start.</xs:documentation>
                                  </xs:annotation>
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:any minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="assessment" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation> Test and exam dates.</xs:documentation>
                                  </xs:annotation>
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:any minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:all>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>

                        <xs:attribute name="number" use="required">
                          <xs:annotation>
                            <xs:documentation> Rule: the day number must be between 1 and 31.</xs:documentation>
                          </xs:annotation>
                          <xs:simpleType>
                            <xs:restriction base="xs:integer">
                              <xs:minInclusive value="1"/>
                              <xs:maxInclusive value="31"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="weekday" use="required">
                          <xs:annotation>
                            <xs:documentation> Weekday name.</xs:documentation>
                          </xs:annotation>
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="Monday"/>
                              <xs:enumeration value="Tuesday"/>
                              <xs:enumeration value="Wednesday"/>
                              <xs:enumeration value="Thursday"/>
                              <xs:enumeration value="Friday"/>
                              <xs:enumeration value="Saturday"/>
                              <xs:enumeration value="Sunday"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>

                  <xs:attribute name="name" use="required">
                    <xs:annotation>
                      <xs:documentation> Full month name.</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="January"/>
                        <xs:enumeration value="February"/>
                        <xs:enumeration value="March"/>
                        <xs:enumeration value="April"/>
                        <xs:enumeration value="May"/>
                        <xs:enumeration value="June"/>
                        <xs:enumeration value="July"/>
                        <xs:enumeration value="August"/>
                        <xs:enumeration value="September"/>
                        <xs:enumeration value="October"/>
                        <xs:enumeration value="November"/>
                        <xs:enumeration value="December"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>

                  <xs:attribute name="month_id" use="required">
                    <xs:annotation>
                      <xs:documentation> Numeric month identifier (1 to 12).</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="12"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="value" type="xs:gYear" use="required">
              <xs:annotation>
                <xs:documentation> The year in YYYY format, for example 2026.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== fabiogabriel5555/GAPE/target/browser-tomcat10/webapps/GAPE/WEB-INF/classes/config/xml/transversal/multiYearCalendar.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../xsl/transversal/multiYearCalendar.xsl"?><calendar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/transversal/multiYearCalendar.xsd">
    <ano value="2025">
        <month month_id="9" name="September">
            <day weekday="Monday" number="1">
                <workday/>
            </day>
            <day weekday="Tuesday" number="2">
                <workday/>
            </day>
            <day weekday="Wednesday" number="3">
                <workday/>
            </day>
            <day weekday="Thursday" number="4">
                <workday/>
            </day>
            <day weekday="Friday" number="5">
                <workday/>
            </day>
            <day weekday="Saturday" number="6">
                <weekend/>
            </day>
            <day weekday="Sunday" number="7">
                <weekend/>
            </day>
            <day weekday="Monday" number="8">
                <workday/>
            </day>
            <day weekday="Tuesday" number="9">
                <workday/>
            </day>
            <day weekday="Wednesday" number="10">
                <workday/>
            </day>
            <day weekday="Thursday" number="11">
                <workday/>
            </day>
            <day weekday="Friday" number="12">
                <workday/>
            </day>
            <day weekday="Saturday" number="13">
                <weekend/>
            </day>
            <day weekday="Sunday" number="14">
                <weekend/>
            </day>
            <day weekday="Monday" number="15">
                <workday/>
            </day>
            <day weekday="Tuesday" number="16">
                <workday/>
            </day>
            <day weekday="Wednesday" number="17">
                <workday/>
            </day>
            <day weekday="Thursday" number="18">
                <workday/>
            </day>
            <day weekday="Friday" number="19">
                <workday/>
            </day>
            <day weekday="Saturday" number="20">
                <weekend/>
            </day>
            <day weekday="Sunday" number="21">
                <weekend/>
            </day>
            <day weekday="Monday" number="22">
                <workday/>
            </day>
            <day weekday="Tuesday" number="23">
                <workday/>
            </day>
            <day weekday="Wednesday" number="24">
                <workday/>
            </day>
            <day weekday="Thursday" number="25">
                <workday/>
            </day>
            <day weekday="Friday" number="26">
                <workday/>
            </day>
            <day weekday="Saturday" number="27">
                <weekend/>
            </day>
            <day weekday="Sunday" number="28">
                <weekend/>
            </day>
            <day weekday="Monday" number="29">
                <workday/>
            </day>
            <day weekday="Tuesday" number="30">
                <workday/>
            </day>
        </month>
        <month month_id="10" name="October">
            <day weekday="Wednesday" number="1">
                <workday/>
            </day>
            <day weekday="Thursday" number="2">
                <workday/>
            </day>
            <day weekday="Friday" number="3">
                <workday/>
            </day>
            <day weekday="Saturday" number="4">
                <weekend/>
            </day>
            <day weekday="Sunday" number="5">
                <holiday>Republic Day</holiday>
            </day>
            <day weekday="Monday" number="6">
                <workday/>
            </day>
            <day weekday="Tuesday" number="7">
                <workday/>
            </day>
            <day weekday="Wednesday" number="8">
                <workday/>
            </day>
            <day weekday="Thursday" number="9">
                <workday/>
            </day>
            <day weekday="Friday" number="10">
                <workday/>
            </day>
            <day weekday="Saturday" number="11">
                <weekend/>
            </day>
            <day weekday="Sunday" number="12">
                <weekend/>
            </day>
            <day weekday="Monday" number="13">
                <workday/>
            </day>
            <day weekday="Tuesday" number="14">
                <workday/>
            </day>
            <day weekday="Wednesday" number="15">
                <workday/>
            </day>
            <day weekday="Thursday" number="16">
                <workday/>
            </day>
            <day weekday="Friday" number="17">
                <workday/>
            </day>
            <day weekday="Saturday" number="18">
                <weekend/>
            </day>
            <day weekday="Sunday" number="19">
                <weekend/>
            </day>
            <day weekday="Monday" number="20">
                <workday/>
            </day>
            <day weekday="Tuesday" number="21">
                <workday/>
            </day>
            <day weekday="Wednesday" number="22">
                <workday/>
            </day>
            <day weekday="Thursday" number="23">
                <workday/>
            </day>
            <day weekday="Friday" number="24">
                <workday/>
            </day>
            <day weekday="Saturday" number="25">
                <weekend/>
            </day>
            <day weekday="Sunday" number="26">
                <weekend/>
            </day>
            <day weekday="Monday" number="27">
                <workday/>
            </day>
            <day weekday="Tuesday" number="28">
                <workday/>
            </day>
            <day weekday="Wednesday" number="29">
                <workday/>
            </day>
            <day weekday="Thursday" number="30">
                <workday/>
            </day>
            <day weekday="Friday" number="31">
                <workday/>
            </day>
        </month>
        <month month_id="11" name="November">
            <day weekday="Saturday" number="1">
                <holiday>All Saints Day</holiday>
            </day>
            <day weekday="Sunday" number="2">
                <weekend/>
            </day>
            <day weekday="Monday" number="3">
                <workday/>
            </day>
            <day weekday="Tuesday" number="4">
                <workday/>
            </day>
            <day weekday="Wednesday" number="5">
                <workday/>
            </day>
            <day weekday="Thursday" number="6">
                <workday/>
            </day>
            <day weekday="Friday" number="7">
                <workday/>
            </day>
            <day weekday="Saturday" number="8">
                <weekend/>
            </day>
            <day weekday="Sunday" number="9">
                <weekend/>
            </day>
            <day weekday="Monday" number="10">
                <workday/>
            </day>
            <day weekday="Tuesday" number="11">
                <workday/>
            </day>
            <day weekday="Wednesday" number="12">
                <workday/>
            </day>
            <day weekday="Thursday" number="13">
                <workday/>
            </day>
            <day weekday="Friday" number="14">
                <workday/>
            </day>
            <day weekday="Saturday" number="15">
                <weekend/>
            </day>
            <day weekday="Sunday" number="16">
                <weekend/>
            </day>
            <day weekday="Monday" number="17">
                <workday/>
            </day>
            <day weekday="Tuesday" number="18">
                <workday/>
            </day>
            <day weekday="Wednesday" number="19">
                <workday/>
            </day>
            <day weekday="Thursday" number="20">
                <workday/>
            </day>
            <day weekday="Friday" number="21">
                <workday/>
            </day>
            <day weekday="Saturday" number="22">
                <weekend/>
            </day>
            <day weekday="Sunday" number="23">
                <weekend/>
            </day>
            <day weekday="Monday" number="24">
                <workday/>
            </day>
            <day weekday="Tuesday" number="25">
                <workday/>
            </day>
            <day weekday="Wednesday" number="26">
                <workday/>
            </day>
            <day weekday="Thursday" number="27">
                <workday/>
            </day>
            <day weekday="Friday" number="28">
                <workday/>
            </day>
            <day weekday="Saturday" number="29">
                <weekend/>
            </day>
            <day weekday="Sunday" number="30">
                <weekend/>
            </day>
        </month>
        <month month_id="12" name="December">
            <day weekday="Monday" number="1">
                <holiday>Restoration of Independence</holiday>
            </day>
            <day weekday="Tuesday" number="2">
                <workday/>
            </day>
            <day weekday="Wednesday" number="3">
                <workday/>
            </day>
            <day weekday="Thursday" number="4">
                <workday/>
            </day>
            <day weekday="Friday" number="5">
                <workday/>
            </day>
            <day weekday="Saturday" number="6">
                <weekend/>
            </day>
            <day weekday="Sunday" number="7">
                <weekend/>
            </day>
            <day weekday="Monday" number="8">
                <holiday>Immaculate Conception</holiday>
            </day>
            <day weekday="Tuesday" number="9">
                <workday/>
